# Generated by Django 5.2.17 on 2026-10-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="slug",
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
    ]
