# Generated by Django 5.2.17 on 2026-10-06 10:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0002_photo_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
